VLWA-922 Staking2.0 (#452)
* add staking 2.0 page in left menu

* add localy staking.2.0 module in the wallet

* update path for staking2.0 module

* updated local staking.2.0 module

* css styles: updated mobile styles

* use staking2.0 npm package instead local one

* add staking2.0 modules into git

* rename Search page to Apps, remove spare tabs list from Apps page

* fix staking path in left menu

* fix mobile menu

* rename

* rename apps to dapps

* Dapps -> DApps

* minor fix VLWA-1346

* tests: [staking] open from dapps

* upd package-json for tests

* tests: remove staking tests skip

* update staking lib version

* tests: setup basic automation structure

* css staking2 updates

* tests: add few tests for staking2.0; extend staking2 screen

* tests: remove deprecated reporters from config; remove allure

* tests: remove allure

* tests: add more tests; extend staking screen

* tests: implement fast login

* tests: sorting, rewards

* tests: update pw ver; remove ts-node

* tests: upd package-lock

* implement search

* tests: rewrite get wallet url function

* tests: add comments

* css minor fix

* rm node_mobules dir from staging

* remove gitignore files

* tests: fix navigation test according to new staking

* ignore tracking of package-lock.json

* use cross-fetch instead node-fetch for browser version

* tests: stake with conversion

* tests: copy validator address

* upd readme

* tests: apply linter changes

* tests: rename test

* pass refresh property to the staking module

* update staking2.0 version to 1.0.16

* add package-lock.json to gitignore

* remove package-lock.json from git

* add package-lock

* update gitignore

* sleep after wallet start

* remove sleep

* add @velas/web3 package.json to gitignore

* add sleep

* add @velas/web3 package.json to gitignore

* remove sleep

* add sleep after wallet start

* upd package-lock

* separate wallet build and start commands

* tests: fix staking 2 tests

* tests: fix walles and navigation tests

* rename staking 2 tests

* disable dai custom token add (cors error)

* rename staking screen; increase staking loader disappearing timeout

* refactor tests and testrun

* fix ci

* fix name

* upd testrun

* fix swap test run

* change node to 14

* test artifact pass

* fix duplicated element found

* add jobs dependency

* fix working dir

* fix work dir

* fix dir

* install lsxc before testrun

* remove extra step

* install node

* skip add custom token on bsc

* rename group

* fix path for e2e

* fix

* test

* fix

* fix art path

* test

* try fixes

* fix .compiled

* test

* fix path for compiled

* test

* test parallel run

* fix testrun

* enable swap tests

* improve enable/disable testnet test stability

* fix failing test

* try to fix enable/disable testnet

* run 2 jobs in parallel

* fix order

* fix skipped

* upd ci

* test

Co-authored-by: Artem P <apindesign@gmail.com>

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -8,7 +8,7 @@ concurrency:
   group: js-wallet-e2e-tests-${{github.event.pull_request.number}}
   cancel-in-progress: true
 jobs:
-  e2e-tests-local-before-merge-to-testnet:
+  swap-tests-on-feature-branch:
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -86,11 +86,15 @@ jobs:
         working-directory: ./
         run: rm -rf ./.compiled
 
-      - name: run wallet
+      - name: build wallet
+        working-directory: ./
+        run: npm run wallet-build
+
+      - name: launch wallet
         working-directory: ./
         run: |
           npm run wallet-start:no-watch &
-          echo '- - - - - Wallet is started but it takes up to 30 seconds to be up - - - - -'
+          echo '- - - - - Wallet is started'
 
       - name: install test npm modules
         run: npm i
@@ -106,13 +110,107 @@ jobs:
       #   run: CI=true npm run balances-api-health-check
 
       - name: check that wallet has started
-        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check previous command output ^" && exit 1)
+        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check outputs of build/run wallet commands" && exit 1)
 
-      - name: clean previous test report
-        run: rm -rf ./test-report/
+      - name: run tests swap
+        run: CI=true npm run test:swap
 
-      - name: run tests
-        run: CI=true npm test
+      - name: upload artifacts
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-report-swap
+          path: |
+            e2e/test-report-swap/
+          retention-days: 6
+  
+  stable-tests-on-feature-branch:
+    runs-on: ubuntu-latest
+    # needs: 'swap-tests-on-feature-branch'
+    defaults:
+      run:
+        working-directory: ./e2e
+    steps:
+      - name: checkout JsWallet
+        uses: actions/checkout@v2
+
+      - name: get branch name
+        run: echo ${{github.event.pull_request.head.ref}} && echo '::set-output name=branch_name::${{github.event.pull_request.head.ref}}'
+        id: get-branch-name
+
+      - name: checkout web3t, testnet branch
+        uses: actions/checkout@v2
+        with:
+          repository: velas/web3t
+          path: .compiled-ssr/web3t
+          ref: testnet
+
+      - name: get PR data
+        id: pr-data
+        uses: velas/get-pull-request-data@master
+
+      - name: try to checkout the same branch for web3t
+        if: contains(steps.pr-data.outputs.title, 'web3t')
+        uses: actions/checkout@v2
+        continue-on-error: true
+        with:
+          repository: velas/web3t
+          path: .compiled-ssr/web3t
+          ref: ${{ steps.get-branch-name.outputs.branch_name }}
+
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '14.x'
+
+      - name: install latest npm
+        run: npm install -g npm@latest
+
+      - name: get node version
+        run: node -v
+      - name: get npm version
+        run: npm -v
+
+      - name: install web3t modules
+        working-directory: .compiled-ssr/web3t
+        run: npm i
+
+      - name: install lsxc
+        run: npm i lsxc -g --unsafe-perm
+
+      - name: copy web3 side by side to wallet
+        working-directory: ../
+        run: rm -rf JsWallet/.compiled-ssr/web3t/.git/objects/ && mkdir -p web3t/ && cp -pr JsWallet/.compiled-ssr/web3t/ ./
+
+      - name: install wallet modules
+        working-directory: ./
+        run: npm i
+
+      - name: delete wallet build cache
+        working-directory: ./
+        run: rm -rf ./.compiled
+
+      - name: build wallet
+        working-directory: ./
+        run: npm run wallet-build
+
+      - name: launch wallet
+        working-directory: ./
+        run: |
+          npm run wallet-start:no-watch &
+          echo '- - - - - Wallet is started'
+
+      - name: install test npm modules
+        run: npm i
+
+      - name: check token providers in default.conf
+        working-directory: ./
+        run: npm run test:check-token-providers-in-default-conf
+
+      - name: check that wallet has started
+        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check outputs of build/run wallet commands" && exit 1)
+
+      - name: run tests stable
+        run: CI=true npm run test:stable
 
       - name: upload artifacts
         if: always()
@@ -121,5 +219,102 @@ jobs:
           name: test-report
           path: |
             e2e/test-report/
-            e2e/test-report-swap/
-          retention-days: 7
+          retention-days: 6
+
+  
+  staking-tests-on-feature-branch:
+    runs-on: ubuntu-latest
+    needs: 'swap-tests-on-feature-branch'
+    defaults:
+      run:
+        working-directory: ./e2e
+    steps:
+      - name: checkout JsWallet
+        uses: actions/checkout@v2
+
+      - name: get branch name
+        run: echo ${{github.event.pull_request.head.ref}} && echo '::set-output name=branch_name::${{github.event.pull_request.head.ref}}'
+        id: get-branch-name
+
+      - name: checkout web3t, testnet branch
+        uses: actions/checkout@v2
+        with:
+          repository: velas/web3t
+          path: .compiled-ssr/web3t
+          ref: testnet
+
+      - name: get PR data
+        id: pr-data
+        uses: velas/get-pull-request-data@master
+
+      - name: try to checkout the same branch for web3t
+        if: contains(steps.pr-data.outputs.title, 'web3t')
+        uses: actions/checkout@v2
+        continue-on-error: true
+        with:
+          repository: velas/web3t
+          path: .compiled-ssr/web3t
+          ref: ${{ steps.get-branch-name.outputs.branch_name }}
+
+      - uses: actions/setup-node@v2
+        with:
+          node-version: '14.x'
+
+      - name: install latest npm
+        run: npm install -g npm@latest
+
+      - name: get node version
+        run: node -v
+      - name: get npm version
+        run: npm -v
+
+      - name: install web3t modules
+        working-directory: .compiled-ssr/web3t
+        run: npm i
+
+      - name: install lsxc
+        run: npm i lsxc -g --unsafe-perm
+
+      - name: copy web3 side by side to wallet
+        working-directory: ../
+        run: rm -rf JsWallet/.compiled-ssr/web3t/.git/objects/ && mkdir -p web3t/ && cp -pr JsWallet/.compiled-ssr/web3t/ ./
+
+      - name: install wallet modules
+        working-directory: ./
+        run: npm i
+
+      - name: delete wallet build cache
+        working-directory: ./
+        run: rm -rf ./.compiled
+
+      - name: build wallet
+        working-directory: ./
+        run: npm run wallet-build
+
+      - name: launch wallet
+        working-directory: ./
+        run: |
+          npm run wallet-start:no-watch &
+          echo '- - - - - Wallet is started'
+
+      - name: install test npm modules
+        run: npm i
+
+      - name: check token providers in default.conf
+        working-directory: ./
+        run: npm run test:check-token-providers-in-default-conf
+
+      - name: check that wallet has started
+        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check outputs of build/run wallet commands" && exit 1)
+
+      - name: run tests staking
+        run: CI=true npm run test:staking
+
+      - name: upload artifacts
+        if: always()
+        uses: actions/upload-artifact@v2
+        with:
+          name: test-report-staking
+          path: |
+            e2e/test-report-staking/
+          retention-days: 6
