VLWA-1152 Refactoring (#420)
* refactor Create wallet test

* refactor auth test: add locators

* add download buttons locators

* refactor balance test

* refactor links test

* refactoring

* refactoring

* fix and refactor wallets test

* refactoring

* refactoring: confirm prompt

* refactoring

* refactor

* apply linter

* add precommit action

* test lint

* test

* remove precommit

* refactoring: common export

* refactor: assert

* refactor: delete outdated github workflow; fix logger work

* refactor: get rid of setup page

* refactoring: replace selectors; add timeout to confirmPrompt method

* add page loading selector

* refactor: delete obsolete code

* update version

* refactor wordByWordSeedInputForm

* add id for sendtx amount input

* fix loader element selector

* refactor swaps: increase speed (-3m); update waitForTx method (add error)

* refactor staking

* fix validators list test

* add separate test results for swap tests

* improve failed swap test logging

* delete unused like from staking

* fix destination network selection in swap

* upd config

* improve error for explorer api

* improve swap tests stability

* improve swap

* rafactor network selection on swap form

* don't wait for confirmation in transaction send test (sometimes it takes up to several minutes)

* configure playwright reporter

* minor: test name update; delete extra logger usage

* test report dirs

* fix artifacts upload for test results

* run prod monitoring test every hour

* apply linter

* remove test-results path from artifacts

* speedify tests

* add cleanup after staking tests

* minor inprovements

* improve logging for stakes diff

* test wallet start check

* fix yaml

* check that wallet started

* add apis healthcheck

* run ts-node using npx

* fix undefined typescript

* remove api health checks

* up

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -27,10 +27,10 @@ jobs:
       - uses: actions/setup-node@v2
         with:
           node-version: '14.x'
-      
-      - uses: joschi/setup-jdk@v2
-        with:
-          java-version: '8'
+
+      # - uses: joschi/setup-jdk@v2
+      #   with:
+      #     java-version: '8'
 
       - name: install web3t modules
         working-directory: .compiled-ssr/web3t
@@ -51,19 +51,23 @@ jobs:
         working-directory: ./
         run: |
           npm run wallet-start:no-watch &
-          echo '- - - - - Wallet is started but it takes till 30 seconds to be up - - - - -'
+          echo '- - - - - Wallet is started but it takes up to 30 seconds to be up - - - - -'
 
-      - name: install npm modules
+
+      - name: install test npm modules
         run: npm i
 
-      - name: clean previous test results
-        run: rm -rf ./test-results/
+      # - name: blockchain health check
+      #   run: CI=true npm run blockchain-health-check
 
-      - name: blockchain health check
-        run: CI=true npm run blockchain-health-check
+      # - name: balances api health check
+      #   run: CI=true npm run balances-api-health-check
 
-      - name: balances api health check
-        run: CI=true npm run balances-api-health-check
+      - name: check that wallet has started
+        run: curl 127.0.0.1:8080 || (echo "ERROR! Walet has not started! Please check previous command output ^" && exit 1)
+
+      - name: clean previous test report
+        run: rm -rf ./test-report/
 
       - name: run tests
         run: CI=true npm test
@@ -72,14 +76,11 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v2
         with:
-          name: test-results
+          name: test-report
           path: |
-            e2e/test-results/
             e2e/test-report/
-            e2e/test-results-swap/
             e2e/test-report-swap/
           retention-days: 7
-
 
       # - name: generate allure report
       #   if: always()
@@ -122,7 +123,7 @@ jobs:
       # - name: post the link to the report
       #   if: always()
       #   uses: Sibz/github-status-action@v1
-      #   with: 
+      #   with:
       #       authToken: ${{secrets.GITHUB_TOKEN}}
       #       context: 'Test report'
       #       state: 'success'
